config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index,except: [:index,:show]
  def index
    @Tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(create_params)
    redirect_to action: :index
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
    redirect_to action: :index
  end

  def edit
    @tweet =Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(create_params) if tweet.user_id == current_user.id
    redirect_to action: :index
  end

 private
  def create_params
    params.require(:tweet).permit(:text,:title,:image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ykkapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <style type="text/css" href="./style.css"></style>
   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  </head>

  <body>
     <nav>
    <div class="nav-wrapper">
      <a href="/tweets" class="brand-logo">Tabigraph.</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "投稿する", "/tweets/new" ,class: "get" %> </li>
        <li><%= link_to "サインアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
        <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
      <% end %>
      </ul>
    </div>
  </nav>
    <%= yield %>
    <script type="text/javascript" src="./app.js"></script>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="row">
  <div class="col s3">
    <div class="card">
      <div class="card-image waves-effect waves-block waves-light">
      <% if tweet.image? %>
        <%= image_tag tweet.image.url %>
      <% end %>
        <!-- <img class="activator" src="images/office.jpg"> -->
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4"><%= tweet.title %></span>
        <p>by <%= tweet.user.name %></p>
        <!-- <p><a href="#">This is a link</a></p> -->
        <div class="card-action">
      <% if user_signed_in? && current_user.id == tweet.user.id %>
            <%= link_to '詳細', tweet_path(tweet.id), method: :get %>
            <%= link_to '編集', edit_tweet_path(tweet.id), method: :get %>
            <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete , data: { confirm: '本当に削除しますか？' } %>
          <% else %>
            <%= link_to '詳細', tweet_path(tweet.id), method: :get %>
      <% end %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="row">
 <!--      <form class="col s12"> -->
    <%= form_for @tweet do |f| %>
        <div class="row">
          <div class="input-field col s6">
            <!-- <input id="input_text" type="text" data-length="10"> -->
            <%= f.text_field :title ,maxlength: 10  %>
            <%= f.label :title, "タイトル" %>
           <!--  <label for="input_text">Input text</label> -->
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <!-- <textarea id="textarea2" class="materialize-textarea" data-length="120"></textarea>
            <label for="textarea2">Textarea</label> -->
            <%= f.text_area :text,maxlength: 140 ,class: "materialize-textarea"%>
            <%= f.label :text,"本文を入力してください" %>
          </div>
        </div>
        <!-- <button class="btn waves-effect waves-light" type="submit" name="action">Submit -->
          <%= button_tag type: "submit", class: "btn waves-effect waves-light" do %>
          Send<i class="material-icons right"></i>
          <% end %>
    <% end %>
    </div>

app/views/tweets/index.html.erb
<div class="row">
  <div class="col s12 ">
    <% @Tweets.each do |tweet| %>
      <%= render partial: "tweet", locals: { tweet: tweet } %>
    <% end %>
  </div>
</div>
<%= paginate(@Tweets) %>

app/views/tweets/new.html.erb
<div class="row">
 <!--      <form class="col s12"> -->
    <%= form_for @tweet do |f| %>
        <div class="row">
          <div class="input-field col s6">
            <!-- <input id="input_text" type="text" data-length="10"> -->
            <%= f.text_field :title ,maxlength: 50 %>
            <%= f.label :title, "タイトル" %>
           <!--  <label for="input_text">Input text</label> -->
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <!-- <textarea id="textarea2" class="materialize-textarea" data-length="120"></textarea>
            <label for="textarea2">Textarea</label> -->
            <%= f.text_area :text,maxlength: 140 ,class: "materialize-textarea" %>
            <%= f.label :text,"本文を入力してください" %>
          </div>
        </div>
        <%= f.label "画像をアップロード" %><br><%= f.file_field :image %>
        <!-- <button class="btn waves-effect waves-light" type="submit" name="action">Submit -->
          <%= button_tag type: "submit", class: "btn waves-effect waves-light" do %>
          Send<i class="material-icons right"></i>
          <% end %>
    <% end %>
    </div>

app/views/tweets/show.html.erb
  <div class="row">
      <div class="col s8 center">
        <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
            <% if @tweet.image? %>
                  <%= image_tag @tweet.image.url %>
          <% end %>
          </div>
        </div>
      </div>
  </div>

  <div class="row">
      <div class="col s12 m6">
        <div class="card  grey lighten-4">
          <div class="card-content black-text">
            <span class="card-title"><%= @tweet.title %></span>
            <p><%= @tweet.text %></p>
          </div>
        </div>
      </div>
    </div>